apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: {{ include "securitymicros.name" . }}
    name: {{ include "securitymicros.name" . }}
spec: 
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ include "securitymicros.name" . }}
    template:
        metadata:
            labels:
                app: {{ include "securitymicros.name" . }}
        spec:
            containers:
            - name: {{ include "securitymicros.name" . }}
              image: {{ .Values.image.repository }}
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "500m"
                  memory: 1Gi
                requests:
                  cpu: "500m"
                  memory: 1Gi
              securityContext:
            imagePullSecrets:
            - name: secret
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{ include "securitymicros.name" . }}
    name: {{ include "securitymicros.name" . }}
spec:
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
    selector:
        app: {{ include "securitymicros.name" . }}
    type: LoadBalancer









